# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160222235923 on 2016-02-23 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_db_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distHour',
            field=models.IntegerField(db_column='dist_hour', default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distMin',
            field=models.IntegerField(db_column='dist_min', default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distSec',
            field=models.IntegerField(db_column='dist_sec', default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='userId',
            field=models.BigIntegerField(db_column='user_id'),
        ),
    ]
