# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160222235923 on 2016-02-26 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_db_service', '0003_auto_20160225_1806'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
    ]
